arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_end_effector
  constraints:
    goal_time: 10.0                     # Override default
    stopped_velocity_tolerance: 0.05    # Override default
    joint_1: {trajectory: 0.1, goal: 0.05}   # Override default
    joint_2: {trajectory: 0.1, goal: 0.05}   # Override default
    joint_3: {trajectory: 0.1, goal: 0.05}   # Override default 
    joint_4: {trajectory: 0.1, goal: 0.05}   # Override default 
    joint_5: {trajectory: 0.1, goal: 0.05}   # Override default
    joint_end_effector: {trajectory: 0.1, goal: 0.05}   # Override default

  stop_trajectory_duration: 0.5         
  state_publish_rate:  50             # Override default
  action_monitor_rate: 30             # Override default
  allow_partial_joints_goal: true     # Override default
  
  gains:
    joint_1:
      p: 220
      d: 1
      i: 4
      i_clamp: 1
    joint_2:
      p: 8000
      d: 20
      i: 25
      i_clamp: 1
    joint_3:
      p: 8000
      d: 20
      i: 85
      i_clamp: 1
    joint_4:
      p: 100
      d: 0.1
      i: 1
      i_clamp: 1
    joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_end_effector:
      p: 100
      d: 0.1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_6
    - joint_7
  gains:
    joint_6:
      p: 1000
      d: 0.1
      i: 1
      i_clamp: 1
    joint_7:
      p: 1000
      d: 0.1
      i: 1
      i_clamp: 1
